import type { ReactElement } from 'react'
import Layout from '@/components/layout/layout'
import type { NextPageWithLayout } from './_app'

import Head from 'next/head'

import Home from '@/components/home'
import About from '@/components/about'
import Services from '@/components/services'
import Contact from '@/components/contact'

const Page: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="App px-4">
        {/* home */}
        <section id="home">
          <Home />
        </section>

        {/* services */}
        <section id="services">
          <Services />
        </section>

        {/* about */}
        <section id="about">
          <About />
        </section>

        {/* contact */}
        <section id="contact">
          <Contact />
        </section>
        
      </main>
    </>
  )
}

Page.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>{page}</Layout>
  )
}

export default Page